config/routes.rb
LbBackend::Application.routes.draw do
  resources :clumps

end

app/models/clump.rb
class Clump < ActiveRecord::Base
  validates :url, presence: true
  validates :url, :format => URI::regexp(%w(http https))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clumps_controller.rb
class ClumpsController < ApplicationController
  before_action :set_clump, only: [:show, :edit, :update, :destroy]

  # GET /clumps
  # GET /clumps.json
  def index
    @clumps = Clump.all
  end

  # GET /clumps/1
  # GET /clumps/1.json
  def show
  end

  # GET /clumps/new
  def new
    @clump = Clump.new
  end

  # GET /clumps/1/edit
  def edit
  end

  # POST /clumps
  # POST /clumps.json
  def create
    @clump = Clump.new(clump_params)

    respond_to do |format|
      if @clump.save
        format.html { redirect_to @clump, notice: 'Clump was successfully created.' }
        format.json { render action: 'show', status: :created, location: @clump }
      else
        format.html { render action: 'new' }
        format.json { render json: @clump.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clumps/1
  # PATCH/PUT /clumps/1.json
  def update
    respond_to do |format|
      if @clump.update(clump_params)
        format.html { redirect_to @clump, notice: 'Clump was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @clump.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clumps/1
  # DELETE /clumps/1.json
  def destroy
    @clump.destroy
    respond_to do |format|
      format.html { redirect_to clumps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clump
      @clump = Clump.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clump_params
      params.require(:clump).permit(:url, :shit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clumps_helper.rb
module ClumpsHelper
end

app/views/clumps/_form.html.erb
<%= form_for(@clump) do |f| %>
  <% if @clump.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clump.errors.count, "error") %> prohibited this clump from being saved:</h2>

      <ul>
      <% @clump.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form role="form">
    <div class="form-group">
      <%= f.label :url %><br>
      <%= f.text_field :url, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :shit %><br>
      <%= f.check_box :shit, class: "checkbox" %>
    </div>
    <div class="">
      <%= f.submit %>
    </div>
</form>
<% end %>

app/views/clumps/edit.html.erb
<h1>Editing clump</h1>

<%= render 'form' %>

<%= link_to 'Show', @clump %> |
<%= link_to 'Back', clumps_path %>

app/views/clumps/index.html.erb
<h1>Listing clumps</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Url</th>
      <th>Shit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clumps.each do |clump| %>
      <tr>
        <td><%= link_to clump.url, clump.url %></td>
        <td><%= clump.shit %></td>
        <td><%= link_to 'Show', clump, class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Edit', edit_clump_path(clump), class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Destroy', clump, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clump', new_clump_path, class: "btn btn-large btn-success" %>

app/views/clumps/new.html.erb
<h1>New clump</h1>

<%= render 'form' %>

<%= link_to 'Back', clumps_path %>

app/views/clumps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @clump.url %>
</p>

<p>
  <strong>Shit:</strong>
  <%= @clump.shit %>
</p>

<%= link_to 'Edit', edit_clump_path(@clump) %> |
<%= link_to 'Back', clumps_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lb Backend" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lb Backend" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
   </main>
  </body>
</html>